<?php

namespace Tests\Unit;

use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class ThreadTest extends TestCase
{
    use RefreshDatabase;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->thread = factory('App\Thread')->create();
    }

    /** @test */
    public function a_thread_can_have_replies()
    {
        $this->assertInstanceOf('Illuminate\Database\Eloquent\Collection', $this->thread->replies);
    }

    /** @test */
    public function a_thread_can_have_creator()
    {
        $this->assertInstanceOf('App\User', $this->thread->owner);
    }

    /** @test */
    public function user_can_add_reply()
    {
        $this->thread->addReply(
            array(
                'body' => 'foo',
                'user_id' => '1'
            )
        );
        $this->assertCount(1, $this->thread->replies);
    }

    /** @test */
    public function thread_get_channel()
    {
        $this->assertInstanceOf('App\Channel', $this->thread->channel);
    }
}
